name: pf_datanote
channels:
  - defaults
dependencies:
  - python=3.9
  - tmap
  - faerun
  - pandas
  - pip
  - pip:
    - git+https://github.com/reymond-group/map4
  - scipy
  - matplotlib
  - ipykernel
  - rdkit
  - requests
  - plotly