name: pf_datanote
channels:
  - conda-forge
  - bioconda
  - defaults
  - nlesc
  - tmap
dependencies:
  - python=3.9
  - ipykernel
  - faerun
  - matchms
  - pandas
  - pip
  - pip:
    - git+https://github.com/reymond-group/map4
  - matplotlib
  - plotly
  - rdkit
  - requests
  - scipy
  - spec2vec
  - tmap
  - r-aplot ## needed by ggtree
  - r-base
  - r-circlize
  - r-dplyr
  - r-ggfortify
  - r-gridExtra
  - r-igraph
  - r-plyr
  - r-readr
  - r-rotl
  - r-rvcheck ## needed by ggtree
  - r-tidytree ## needed by ggtree